### ISSUE TITLE
TimeDistributed ValueError: total size of new array must be unchanged

### ISSUE THREAD

**Issue by joyicejin** [WoongheeLee/DeepSleepNet_Implementation_in_Keras#2]
First, thank you very much for your implementation in keras.
But when I run the model, I got the TimeDistributed Error for the finetune network. Could you help me to debug this?
keras version:2.2.2
python version:3.6
tensorflow-gpu:1.9
data_formate: channel_first

1. run the code:
 `python deepsleepnet.py`
2.you can get the error info for TimeDistributed network layers in code :
` signal_sequence = TimeDistributed(cnn_part)(input_seq)  #`
3. the error is:
```
Traceback (most recent call last):
  File "D:/3/mobilenet/DeepSleepNet-master/DeepSleepNet_Implementation_in_Keras-master/deepsleepnet.py", line 152, in <module>
    seq_model = deepsleepnet(pre_model)
  File "D:/3/mobilenet/DeepSleepNet-master/DeepSleepNet_Implementation_in_Keras-master/deepsleepnet.py", line 121, in deepsleepnet
    signal_sequence = TimeDistributed(cnn_part)(input_seq)  # TimeDistributed
  File "C:\Users\lenovo\Anaconda3\envs\tfjs_gpu_tfjs\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 703, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "C:\Users\lenovo\Anaconda3\envs\tfjs_gpu_tfjs\lib\site-packages\tensorflow\python\keras\layers\wrappers.py", line 225, in call
    output_shape = self.compute_output_shape(input_shape).as_list()
  File "C:\Users\lenovo\Anaconda3\envs\tfjs_gpu_tfjs\lib\site-packages\tensorflow\python\keras\layers\wrappers.py", line 179, in compute_output_shape
    child_input_shape).as_list()
  File "C:\Users\lenovo\Anaconda3\envs\tfjs_gpu_tfjs\lib\site-packages\tensorflow\python\keras\engine\network.py", line 784, in compute_output_shape
    output_shape = layer.compute_output_shape(input_shapes[0])
  File "C:\Users\lenovo\Anaconda3\envs\tfjs_gpu_tfjs\lib\site-packages\tensorflow\python\keras\layers\core.py", line 435, in compute_output_shape
    self.target_shape)
  File "C:\Users\lenovo\Anaconda3\envs\tfjs_gpu_tfjs\lib\site-packages\tensorflow\python\keras\layers\core.py", line 423, in _fix_unknown_dimension
    raise ValueError(msg)
ValueError: total size of new array must be unchanged
```
![image](https://user-images.githubusercontent.com/32789540/58086775-d9079b80-7bf1-11e9-9e21-3e52d5716276.png)

**Comment by WoongheeLee** [comment]
Hi, I tried to reproduce the error in the environment (keras=2.2.2, python=3.6, tensorflow-gpu=1.9, ubuntu 16), but I couldn't. I think you change some lines.

Because the error message is usually caused by shape discrepancy between two layers, you can debug the code using print each shape for each layers.

I commented out "print(layer.shape)". You can use this. 

Plus, the model is designed to input shape (batch size, 3000, 1) for featurenet() and (batch size, 25, 3000, 1) for deepsleepnet().

You should probably some parameters.

Thanks.

**Comment by joyicejin** [comment]
Ok, thanks! I tried in ubuntu, it does no error occurs, but it still happens on windows, It's really confused
